### PR TITLE
Selection highlight should extend behind the Details... button #54

### LINKED ISSUE #54: Selection highlight should extend behind the Details... button
#### Software versions 
Briefcase v1.4.9, Java 1.8.0_112-b16, macOS 10.12.3

#### Problem description
screen shot 2017-01-11 at 9 56 00 am

#### Steps to reproduce the problem
Click on a form row.

#### Expected behavior
The row highlight should continue under the button.

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #54 
snip20170305_3

But could someone cross check on windows pls.

### CODE REVIEW

**Comment by lognaturel** [comment]
@yanokwa Do you have a Windows VM that you could double check this on quickly?

**Comment by lognaturel** [comment]
Oh, a question for you @rclakmal! Can you maintain that highlight behavior but make sure the background behind unselected buttons is white?

**Comment by rclakmal** [comment]
@lognaturel Done :)
snip20170306_5

**Comment by yanokwa** [comment]
Confirmed working in Windows 7 and Windows 10. I think this is ready to merge, @lognaturel.

**Comment by lognaturel** [comment]
Thanks very much @rclakmal and congrats on your first merged pull request!! I saw your message in the #gsoc Slack channel, it's very nice to meet you. Please let us know if you have any questions as you're exploring the code base and working on your project proposal! 🎉

**Pull request merged**
