### PR TITLE
Replace tabs with spaces

### LINKED ISSUE #131: Replace tabs with spaces
The following classes have tabs that should be replaced with spaces. 
```
AggregateUtils.java
BadFormDefinition.java
BriefcaseFolderChooser.java
BriefcaseStorageLocationDialog.java
DatabaseUtils.java
ExportFolderChooser.java
ExportType.java
FormDefinitionFileChooser.java
FormTransferTable.java
HtmlConsts.java
HtmlStrUtil.java
LegacyServerConnectionDialog.java
MainBriefcaseWindow.java
ODKCollectFileChooser.java
PrivateKeyFileChooser.java
PushTransferPanel.java
ServerConnectionDialog.java
ServerFetcher.java
StringUtils.java
TransferFromODK.java
TransferInProgressDialog.java
WebUtils.java
XFormParameters.java
```

Use IntelliJ's conversion tool to convert the tabs with spaces, then uncomment out the following in checkstyle.xml.
```
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
```

Run `./gradlew checkstyle` and fix any remaining issues.

To make code review easy, please make sure the PR has mostly whitespace changes.

### PR DESCRIPTION
**Pull request by yanokwa**
Closes #131

#### What has been done to verify that this works as intended?
Ran `./gradlew check` and `./gradlew run` to make sure there are no errors and the application runs. https://github.com/opendatakit/briefcase/pull/134 was an old PR that I closed because of inactivity with the same approach.

#### Why is this the best possible solution? Were any other approaches considered?
I couldn't find a nice way to do this in IntelliJ, so the command I used was from https://stackoverflow.com/a/11094620/152938.
`find . -name '*.java' ! -type d -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;`

#### Are there any risks to merging this code? If so, what are they?
There might be some place where a tab is inside a string, but that's why I used [expand](https://man.cx/expand), not sed.

### CODE REVIEW

**Comment by lognaturel** [comment]
@dcbriccetti @daveycrockett @nribeka How do you all feel about this being merged now? We have relatively few opened PRs so it might be a good time to get it done. Or perhaps we can finish and merge @daveycrockett's #139 first? I think he might be gone on 🏝vacation🏝 but perhaps they're small enough things that I can push to his branch.

**Comment by dcbriccetti** [comment]
It would be nice to get #139 put away. My only concerns are avoiding a lot of work that these should-be-trivial changes can cause. It’s nice when they happen when there are no unmerged branches active.

**Comment by lognaturel** [comment]
Yeah, you're totally right. Let's see if we can get both the open ones in before we do this.

**Comment by yanokwa** [comment]
Closing because I'd rather https://github.com/opendatakit/briefcase/pull/183 gets merged so that contributor gets his first ODK PR.

**Pull request closed without merging**
