### PR TITLE
Convert tabs to spaces. Fix #131.

### LINKED ISSUE #131: Replace tabs with spaces
The following classes have tabs that should be replaced with spaces. 
```
AggregateUtils.java
BadFormDefinition.java
BriefcaseFolderChooser.java
BriefcaseStorageLocationDialog.java
DatabaseUtils.java
ExportFolderChooser.java
ExportType.java
FormDefinitionFileChooser.java
FormTransferTable.java
HtmlConsts.java
HtmlStrUtil.java
LegacyServerConnectionDialog.java
MainBriefcaseWindow.java
ODKCollectFileChooser.java
PrivateKeyFileChooser.java
PushTransferPanel.java
ServerConnectionDialog.java
ServerFetcher.java
StringUtils.java
TransferFromODK.java
TransferInProgressDialog.java
WebUtils.java
XFormParameters.java
```

Use IntelliJ's conversion tool to convert the tabs with spaces, then uncomment out the following in checkstyle.xml.
```
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
```

Run `./gradlew checkstyle` and fix any remaining issues.

To make code review easy, please make sure the PR has mostly whitespace changes.

### PR DESCRIPTION
**Pull request by thomashhuang**
Closes #131 

#### What has been done to verify that this works as intended?
Uncommented FileTabCharacter in checkstyle.xml, all other changes were conversions form tabs to spaces. Ran "./gradlew" tests, no errors.

#### Why is this the best possible solution? Were any other approaches considered?
Used IntelliJ indentation conversion, as recommended in the initial Issue comment.

#### Are there any risks to merging this code? If so, what are they?
Used IntelliJ indentation conversion, should be no risk.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
We have a big merge outstanding. It would be far easier to redo this, then resolve conflicts it may cause with the merge. Can we hold off?

**Comment by thomashhuang** [comment]
@dcbriccetti @lognaturel as requested, rebased #179 on top of the whitespace changes to #183. Everything seems to have worked out pretty cleanly.

**Comment by lognaturel** [comment]
Hi @thomashhuang! Thanks so much for doing this and so sorry it became complicated! With these kinds of changes that affect a whole bunch of files timing can be tricky.

All other open pull requests have been merged so now would be a FANTASTIC time to get this in. What I would probably do now is fetch upstream, reset to upstream/master and reapply the fix. Or alternately, it might be even easier to just create a new branch and pull request.

**Comment by lognaturel** [comment]
Replaced by #193

**Pull request closed without merging**
