### PR TITLE
Issue 258 last export date

### PR DESCRIPTION
**Pull request by ggalmazor**
Partially addresses #258 

This PR is built on top of #272 because it uses the Preferences saving/loading infrastructure for the Export tab

briefcase_last_export_date

Now the forms table has a new column that will track the last export date between launches.

Export dates will be tracked while using both the GUI and CLI command.

The export date will be formatted according to the user's locale.

#### What has been done to verify that this works as intended?
Manual tests

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### Are there any risks to merging this code? If so, what are they?
None I'm aware of

### CODE REVIEW

**Comment by lognaturel** [comment]
Works well. 👍 Can you please rebase on master so we can keep history clean when merging?

**Comment by ggalmazor** [comment]
Good to go :)

**Comment by yanokwa** [comment]
@ggalmazor I'm happy to merge this after the conflicts are resolved!

**Comment by ggalmazor** [comment]
Ready to go :)

**Pull request merged**
