### PR TITLE
Pack connection dialog

### LINKED ISSUE #312: Aggregate Server Connection window needs resizing to read text below login fields.
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system Windows and Ubuntu.

#### Problem description
Displayed window where you can log in to aggregate account needs resizing if you want to read information below login fields. 

#### Steps to reproduce the problem
1. Go to pull or push section
2. Click on Connect button.
3. Aggregate Server Connection window should display now.

#### Expected behavior
Information below fields should be present in the window all the time without resizing as it is displayed on MacOS.

#### Other information 
Screenshot of problem on Windows, in the left side there is window which appears, and in the right resized one. 
aggregate connection_win

On MacOs information is not cut and looks like that:
aggregate connection

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #312

This PR packs the dialog to accommodate everything inside.

It also makes the fields a little bit wider and centers the dialog on screen

#### What has been done to verify that this works as intended?
Manual tests

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### Are there any risks to merging this code? If so, what are they?
N/A

### CODE REVIEW

**Comment by yanokwa** [comment]
What platform was this tested on?

**Comment by ggalmazor** [comment]
Linux and now I'm trying mac... Will have feedback on some minutes

**Comment by ggalmazor** [comment]
Mac checked (also checked #316)

**Comment by ggalmazor** [comment]
Windows 10 checked (also checked #316)

**Comment by dcbriccetti** [comment]
If you undo this:
undo set sizes

It looks like this:
after undo set sizes

That looks right to me.

**Pull request merged**
