### PR TITLE
On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a disabled main window #87

### LINKED ISSUE #87: On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a disabled main window
#### Software versions 
Briefcase v1.4.10, Java 1.8, OS Windows 7

#### Problem description
On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a totally disabled main window. 

#### Steps to reproduce the problem
1. Just delete/move the briefcase storage directory and relaunch the app. You will get the storage location selection popup
2. Press "Cancel"
3. You are end up on a disabled main window with no option of going back. Only option is to close and relaunch. 

b1

b2

#### Expected behavior
This would probably get fixed over the summer project for unified ui. A quick fix would be to remove the "Cancel" button. Because as of now, it doesn't serve any purpose

### PR DESCRIPTION
**Pull request by rclakmal**
Fixes #87

How to test
1. Move/Rename your briefcase storage.
2. Start ODK briefcase. You will see the folder selection dialog. 
3. Press Cancel. Application should quit. Restart the briefcase dialog. You should still see the folder selection dialog
4. This time choose a proper folder and press ok. App should be enabled.

### CODE REVIEW

**Comment by yanokwa** [comment]
I'm very happy with this change for the start case, but remember that in Settings, you can change the storage location. In the settings case, the dialog should say Cancel.

**Comment by rclakmal** [comment]
@yanokwa Handled the situation of dialog getting triggered from Settings page. This is open for review again.

**Comment by yanokwa** [comment]
I'm pretty happy with this functionality, @rclakmal. Great job!

@lognaturel Can you do a code review?

**Comment by lognaturel** [comment]
🙌 Thank you @rclakmal!

**Pull request merged**
