### PR TITLE
UX clean up for overwrite existing files feature

### LINKED ISSUE #409: UX clean up for overwrite existing files feature
- [ ] Remove icon on confirmation dialog https://github.com/opendatakit/briefcase/pull/404#issuecomment-371435677
- [ ] ~~Add title to confirmation dialog https://github.com/opendatakit/briefcase/pull/404#issuecomment-371511483~~
- [ ] Add vertical spacer https://github.com/opendatakit/briefcase/pull/404#issuecomment-371450318

### PR DESCRIPTION
**Pull request by emajj**
Closes #409 

#### What has been done to verify that this works as intended?
Manually tested on Linux

#### Are there any risks to merging this code? If so, what are they?
None

### CODE REVIEW

**Comment by emajj** [comment]
@ggalmazor I merged your commit using `git merge ggalmazor/pr_404_layout` Inside my git log, I have just to commits for this issue. One of the commits is a merge commit. It's on GitHub that it shows 3 commits so not show how to squash. The first two commits show up as one commit from the terminal

> commit 50d57ad8abdd181cff9e58fad0f8fdfdaa686d0d
> Merge: 7323df3 2b69d95
> Author: Eyisab Majj <emajj25@gmail.com>
> Date:   Sat Mar 10 01:40:12 2018 +0100
> 
>     Merge remote-tracking branch 'ggalmazor/pr_404_layout' into issue-409
>     
>     Add vertical spacer above new field
>

**Comment by ggalmazor** [comment]
You're right! Let's approve this :)

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs testing"

**Comment by lognaturel** [comment]
Don’t worry about our friend @opendatakit-bot, @emajj, ze can get a little impatient. 😆 QA verification should happen very soon.

**Comment by kkrawczyk123** [comment]
### Tested with success!
Verified on Ubuntu, MacOS and Windows.
It's much better after removing this ugly icon !

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
