### PR TITLE
Issue 325 Fix order of datepicker and error dialogs in the window stack

### LINKED ISSUE #325: Export configuration error message dialog shows below date
#### Software versions 
Briefcase v1.8.0-232, Java v1.9, macOS 10.13 or Windows 10

#### Steps to reproduce the problem
When attempting an export, select an end date that is after a start date. An "Export configuration error" dialog will pop up. The error message will show up behind the date chooser. Depending on your configuration, the "OK" will be hidden. 

#### Expected behavior
The error message is on top of all windows.

#### Other information 

screen shot 2018-01-28 at 20 46 21

screen shot 2018-01-28 at 20 46 33

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #325

#### What has been done to verify that this works as intended?
Manual tests

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### Are there any risks to merging this code? If so, what are they?
N/A

### CODE REVIEW

**Comment by ggalmazor** [comment]
It seems that today is "Java on Mac appreciation day". Same code on both datepickers behaves differently. Also, the same code behaves as expected on Linux :(

**Comment by ggalmazor** [comment]
Confirmed that it works on linux, mac and win10

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on linux, mac and windows with the same result.

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
