### PR TITLE
Made startup message for ODK friendlier and easier to understand. 

### PR DESCRIPTION
**Pull request by darshan934**
Fix for Improve startup message #358
(https://github.com/opendatakit/briefcase/issues/358)

Closes #

### CODE REVIEW

**Comment by ggalmazor** [comment]
Hi @darshan934! Thanks for your contribution.

Unfortunately, GitHub thinks your commit https://github.com/opendatakit/briefcase/pull/415/commits/9a6d208622e2b95be19bae36e32eba05200e2e33 changes the whole `MessageStrings` class for some reason.

I've tested copying your changes and creating a PR to see what would happen (check #416). In my PR the diff is correct. Could you recreate the changes on your branch and force push it to see if the problem goes away, please?

**Comment by lognaturel** [comment]
One additional thing -- though I like "4. And always remember to have fun!" I think some users may not like it as much. I know there is some general distaste for overly cheerful software!

**Comment by darshan934** [comment]
I have reuploaded the file and removed the overly friendly message (I agree with what you said @lognaturel ), hopefully it should merge this time.

**Comment by darshan934** [comment]
sorry I accidentally closed the PR, you can merge it now

**Comment by lognaturel** [comment]
Thanks, @darshan934! The reason your diff wasn't making sense is because you had moved the file to the root of your code directory. Make sure you run your changes before submitting a PR! I moved the file back, added a missing semicolon and fixed checkstyle issues.

You made changes to your `master` branch so I suggest doing a `git reset upstream/master` and then `git push --force` to get back in sync with the root. You can then create branches for any future features you look at.

**Pull request merged**
