### PR TITLE
Fix #372 - Migrate some Listeners to Adapters

### LINKED ISSUE #372: Migrate some Listeners to Adapters
Sometimes, we don't really care for all the events a Swing `Listener` object can receive. This is an example on `PullTransferPanel` (line 235):

```java
txtOriginName.addFocusListener(new FocusListener() {
  @Override
  public void focusGained(FocusEvent e) {
    // don't care...
  }

  @Override
  public void focusLost(FocusEvent e) {
    if (txtOriginName.isEditable()) {
      PullTransferPanel.this.updateFormStatuses();
    }
  }
});
```

This `Listener` could be replaced with an `Adapter`, which doesn't force you to implement all its methods:

```java
txtOriginName.addFocusListener(new FocusAdapter() {
  @Override
  public void focusLost(FocusEvent e) {
    if (txtOriginName.isEditable()) {
      PullTransferPanel.this.updateFormStatuses();
    }
  }
});
```

Searching in the project with the regular expression "new \w+Listener\(" will produce a list of places to check for this.

### PR DESCRIPTION
**Pull request by mayank8318**
Closes #372 

#### What has been done to verify that this works as intended?
Passes all the existing tests. Also, just migrated listeners to adapters and removed empty overridden methods. So shouldn't have broken anything.

#### Why is this the best possible solution? Were any other approaches considered?
Nope

#### Are there any risks to merging this code? If so, what are they?
None that I can think of

### CODE REVIEW

**Comment by mayank8318** [comment]
@ggalmazor I could find just two

**Comment by mayank8318** [comment]
Most of those implementations do not have empty methods. Should I still change those?

**Comment by ggalmazor** [comment]
Yes, review them and remove what's not used. Specifically:
- JTableButtonMouseListener: All but mouseClicked
- ProxyChangeListener: I think replacing all uses of this with an inlined FocusAdapter or ChangeListener would work really well
- MouseListenerBuilder: All but mouseClicked
- WindowAdapterBuilder: All but windowClosing

**Comment by mayank8318** [comment]
My bad didn't realize that the callbacks were blank

**Comment by mayank8318** [comment]
@ggalmazor I have updated the PR :)

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
**Tested with success!**
OS: Ubuntu, MacOs and Windows
I was just looking for any regression and I didn't find anything suspicious so I think it's good to go. 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
