### PR TITLE
Issue 599 custom export conf boolean ui control

### LINKED ISSUE #599: Improve custom export conf boolean param UI controls
Related to #587 

YES/NO export conf params can be overridden by selecting choices from a drop-down select box: INHERIT, YES or NO.

image

Drop-down selects look kind of bulky and hard to use

Lets change these controls to inlined radio buttons which show all options readily visible, use less space and are easier to translate:

image

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #599 (and #587)

This PR changes the UI of the boolean conf params of the custom export configuration dialog to show three inlined radio buttons:

image

It also brings code changes to reduce duplication around the concept of a boolean (TRUE/FALSE) value than can be overriden. New artifacts (and tests) have been created to support this model:
- `OverridableBoolean`: Class adapted to the context of Briefcase's domain, that represents a Boolean value that could be overriden by some other Boolean value.
- `TriStateBoolean`: Class that represents a Boolean value with a third UNDERTERMINED state.
- `CustomConfBooleanForm`: UI component to choose between INHERIT, YES, and NO options (radio buttons, currently).

Some of this PR's commits feel big. I wasn't sure how to further split them without having commits that would not compile... I think that stepping through the commits and reviewing the changes on IntelliJ would help. Any and all feedback will be welcome so that I can restructure the PR into more manageable pieces.

#### What has been done to verify that this works as intended?
Run automated tests.
Manually verified that all combinations of boolean conf params work as expected between launches (see #581 for reference of which combinations):

| Default | Custom | Resolved to |
|---|---|---|
|ON|INHERIT|ON|
|ON|ON|ON|
|ON|OFF|OFF|
|OFF|INHERIT|OFF|
|OFF|ON|ON|
|OFF|OFF|OFF|

#### Why is this the best possible solution? Were any other approaches considered?
This, one one hand, brings a UI improvement as discussed in the forums. It is conformant to other UI components currently available.

On the other hand, the export configuration is becoming bigger and by solving #587, we were introducing the third instance of a duplicated structure, which forced some cleaning of the design.

#### Are there any risks to merging this code? If so, what are they?
This change is big and I could have introduced new bugs/regressions. Thorough manual tests are recommended.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Looking at this now

**Comment by ggalmazor** [comment]
Thanks, @dcbriccetti! I've added some commits to avoid losing prefs. Now it should be ready to merge.

**Comment by dcbriccetti** [comment]
@ggalmazor, what about the failing test?

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
Verified on Ubuntu, MacOS and Windows.
Regression has been found, one is already fixed in https://github.com/opendatakit/briefcase/pull/607 and another one reported in https://github.com/opendatakit/briefcase/issues/608.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by ggalmazor** [comment]
Thanks, @kkrawczyk123!

**Pull request merged**
