### PR TITLE
util/ExportToCsv: On export, only create media folder when needed

### LINKED ISSUE #70: On export, only create media folder when needed
On export to CSV, Briefcase creates a media folder whether or not there is media associated with the file. It should only create a media folder when there is media.

### PR DESCRIPTION
**Pull request by shivam-tripathi**
Shift the code portion creating media folder to emitSubmissionCsv (to the case where binary data is being handled).

Fix #70

### CODE REVIEW

**Comment by rclakmal** [comment]
@shivam-tripathi Just a little comment from my side, since I was also looking at this issue. 
With your current fix, the check for `if (!outputMediaDir.exists())` will happen for each media file right ?

Can we use the `FileSystemUtils.getMediaDirectoryIfExists` to verify the existence of media directory in the form folder getting exported and keep the check at its original location?
```

    if (exportMedia && FileSystemUtils.getMediaDirectoryIfExists(briefcaseLfd.getFormDirectory())!=null) {
       if (!outputMediaDir.exists()) {
         if (!outputMediaDir.mkdir()) {
           EventBus
               .publish(new ExportProgressEvent("Unable to create destination media directory"));
           return false;
         }
       }
    }
```
WDYT ? :)

**Comment by yanokwa** [comment]
@shivam-tripathi @rclakmal Also note thatif you have three if's you can just and them.. 

```
if (exportMedia) {
   if (!outputMediaDir.exists()) {
     if (!outputMediaDir.mkdir()) {
```
```
if (exportMedia && !outputMediaDir.exists() && !outputMediaDir.mkdir())
```

**Comment by shivam-tripathi** [comment]
@rclakmal Makes sense. 
@yanokwa Will modify.

**Comment by yanokwa** [comment]
Hi @shivam-tripathi! Have you had a chance to make these changes?

**Comment by shivam-tripathi** [comment]
@yanokwa Following relevant discussion on https://github.com/opendatakit/briefcase/issues/70.
Does this work with the CLI? If yes, I will make relevant changes in the code style. If no, then further looking into this would be needed.

**Comment by yanokwa** [comment]
Hi @shivam-tripathi, I can confirm this works with the CLI. I don't know what happened, but sorry about that!

**Comment by lognaturel** [comment]
Thank you, @shivam-tripathi!

**Pull request merged**
