### PR TITLE
Remove explicit type arguments

### PR DESCRIPTION
**Pull request by emajj**
Fixes https://github.com/opendatakit/briefcase/issues/370

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Hi. Circle CI gave you this error:
:checkstyleMain[ant:checkstyle] [ERROR] /home/circleci/work/src/org/opendatakit/briefcase/util/ExportToCsv.java:37:8: Unused import - java.util.Comparator. [UnusedImports]

**Comment by emajj** [comment]
Fixed.

**Comment by dcbriccetti** [comment]
Looks good, but you missed one in BaseFormParserForJavaRosa. I found it running an inspection with IDEA.

**Comment by dcbriccetti** [comment]
Thanks for improving the code, @emajj.

**Pull request merged**
