### PR TITLE
Sentry integration

### PR DESCRIPTION
**Pull request by ggalmazor**
This PR integrates Briefcase with Sentry through its logback appender option.

#### What has been done to verify that this works as intended?
Manually run Briefcase, both UI and CLI and produced some errors by exporting an encrypted form without providing a valid PEM file. The errors should get into Sentry's dashboard.

#### Why is this the best possible solution? Were any other approaches considered?
Sentry has other ways to send errors but this was the most transparent one (one which requires close to zero code changes).

Other options require using older logging frameworks like log4j or directly using Sentry's SDK, which would produce duplication on error logging.

#### Are there any risks to merging this code? If so, what are they?
None.

### CODE REVIEW

**Comment by lognaturel** [comment]
This will be so helpful to have! I've verified that both explicitly logged errors and fatal crashes are sent up. 

Would it be worth including a release build variant that uses the Sentry logback config? It seems like the kind of thing that will be really easy to forget otherwise and then we'd miss out on useful logging.

**Comment by yanokwa** [comment]
@lognaturel I think that the existing setup is fine for release. That is, I have a separate folder hierarchy where I generate the release builds and so as long as logback.xml isn't committed to the repo, I can configure that folder hierarchy once and the building for release should be bulletproof.

Thanks for your review! I'll fix the conflicts and get this merged.

**Comment by ggalmazor** [comment]
Yes, let's do that. I've had to do the same with #354...

**Comment by ggalmazor** [comment]
I accidentally remove the branch on the fork and now I have to create a new PR, sorry! #381

**Pull request closed without merging**
